services:
  rarchbot:
    image: docker-registry:5000/rarchbot:latest
    environment:
      TELOXIDE_TOKEN: ${TELOXIDE_TOKEN}
      DB_PATH: /docker_data/app.db
      URL: https://archlinux.org/feeds/news/
    volumes:
      - docker_data:/docker_data
    restart: unless-stopped

volumes:
  rarchbot-data:
